apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-home
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>

    <h1>Gabs NGINX with Helm Chart Version</h1>

    <p>Current Version: {{ .Chart.Version }}</p>

    </body>
    </html>
