apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx_with_version_page.fullname" . }}
  namespace: {{.Values.namespace}}
  labels:
    {{- include "nginx_with_version_page.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx_with_version_page.selectorLabels" . | nindent 4 }}
